# Generated by Django 5.0.3 on 2024-03-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_rename_adress_client_address_alter_client_reg_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(max_length=200),
        ),
    ]
