# Generated by Django 5.0.3 on 2024-04-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_alter_item_image_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to='media/'),
        ),
    ]
